### ISSUE TITLE
Marks values are rounded up

### ISSUE THREAD

**Issue by simonapostolovski** [antoniolago/react-gauge-component#18]
Hi, so I'm adding my marks and subArcs values dynamically, basically some math is done to create one default mark as a value and then split the range equally to create at least 3 equal zones.

Marks:

![image](https://github.com/antoniolago/react-gauge-component/assets/104428022/5661e319-7cdf-4dce-ad9c-da8d073e0477)

subArcs:

![image](https://github.com/antoniolago/react-gauge-component/assets/104428022/4908a4b3-2d47-4952-a638-d26c58fb8895)

Im working with values up to 1 so im multiplying all of them * 100.

And this is what i get:

![image](https://github.com/antoniolago/react-gauge-component/assets/104428022/6faf9ed6-1fbf-4a14-9b03-506d49dab4ca)

Check the zones, the 3 zones after 0.2 should be equal, but the gap is 0.3, 0.2, 0.3 and its not split evenly.

My issue is that the values are rounded to the nearest. Its suppost to be 0.46 but its 0.5 mark, 0.73 but its 0.7, and its messing up the equal zones.

Any way the value rounding can be skipped? I checked the value format function but it doesn't work on this.

**Comment by antoniolago** [comment]
Hello, sorry for the late response.
I added a `maxDecimalDigits` property to both marks labels and value label. 
please try the new version 1.1.11 and let me know if this works for u :)
