### ISSUE TITLE
Changes in the attribute 'color' in Pointer doesn't seems to change color

### ISSUE THREAD

**Issue by tfonrouge** [antoniolago/react-gauge-component#21]
Hi,

Seems that the pointer 'color' attribute doesn't work with gauge types [semicircle, radial] on grafana the change in the attribute correctly changes the stripe color.

However, on [semicircle, radial] gauge types, the change in the pointer color attribute correctly changes the outer color ring but only when the pointer type is 'blob'

I'm using the library under Kotlin / KVision

Thanks in advance and congratulations for an excellent and complete gauge library

Teo Fonrouge

**Comment by antoniolago** [comment]
Hello, I'm short of free time lately and this kind of contribution really helps because sometimes I don't even know something is broken given the many props possible in the component, so thanks for the contribution. That said, I'll take it a look when I get some time, but it should be an easy fix, feel free to PR it if you find it before me.

**Comment by antoniolago** [comment]
Hey @tfonrouge, I wasn't able to reproduce the issue, can you provide me some screenshots and the code you used?

**Comment by tfonrouge** [comment]
Hi @antoniolago , sorry for late response. 

I'm using Kotlin KVision library (https://github.com/rjaros/kvision) which imposes a abstract layer over JavaScript frontend, that said, I have to admit that I must build a sample in pure Js to avoid any possible problem from which I'm unaware of derivated from the process of import your  'react-gauge-component'.

So it's very possible that a bug/feature in my process is the origin of the problem.

I'll close this issue until I've successfully reproduced it in pure Js sample, or to find out the problem is mine :-) (in which case I'll also report it here).

Thanks and sorry for the poor issue reported.

Teo Fonrouge

**Comment by antoniolago** [comment]
Hello Teo, understood, unfortunately I'm not familiar with kvision, but I look forward to know your findings. 
You're welcome, and do not be sorry :)
