### ISSUE TITLE
Namespace React has no exported member JSX

### ISSUE THREAD

**Issue by simonapostolovski** [antoniolago/react-gauge-component#27]
After doing `npm run build` it runs `concurrently npm:build:*` that runs `build:types` which basically just runs the `tsc` command behind the scenes.

There seems to be a typescript error in the react-gauge-component and `build:types` exits with code 1 but the build continues on with no issues, however this shouldn't be overlooked and should be fixed.

The second error `node_modules/react-i18next/ts4.1/index.d.ts(8,3): error TS2614: Module '"i18next"' has no exported member 'TFunctionResult'. Did you mean to use 'import TFunctionResult from "i18next"' instead?` isn't related to this component though and can be ignored.

I have   `"react": "^16.13.1"`, `"@types/react": "^16.14.24"` and TypeScript 4.9.5

![image](https://github.com/antoniolago/react-gauge-component/assets/104428022/25becdbc-e331-4283-9f95-0b3beead4d28)
![image](https://github.com/antoniolago/react-gauge-component/assets/104428022/75988f3a-2e52-4239-b4bc-89e28520736b)

**Comment by antoniolago** [comment]
Hello, thanks for reporting this.
I was not able to reproduce your error, but the project did had a lot of ts errors regarding react 17, so I followed the steps mentioned in https://github.com/expo/expo/issues/17101 and those ts errors went away, maybe it did fixed the error you're seeing in this new 1.1.30 release, please let me know.

**Comment by simonapostolovski** [comment]
I still have the error, it could be that I'm still on `"react": "^16.13.1"` but I can't upgrade the project at the moment.
Its no problem thanks for checking.

**Comment by antoniolago** [comment]
Yeah sure, I'll try to spare some time to check the types compatibilities in react v16, feel free to reopen the issue anytime
