### ISSUE TITLE
Gradient Fails for Negative Values

### ISSUE THREAD

**Issue by ianpotpie** [antoniolago/react-gauge-component#28]
Seems like it may be using the gradient on a scale of 0-100 even when the min/max values are changed.

![image](https://github.com/antoniolago/react-gauge-component/assets/30676689/c5dd1c54-8e1e-4d3a-a7af-817fb4e4d2de)

![image](https://github.com/antoniolago/react-gauge-component/assets/30676689/f0785b36-8731-415f-9a26-0921e79d26dd)

**Comment by antoniolago** [comment]
Hello, thanks for reporting this,

For now I'll leave it open to anyone contribute until I get the chance to fix this
