### ISSUE TITLE
Hiding tick lines doesn't seem to work

### ISSUE THREAD

**Issue by andrewjafa** [antoniolago/react-gauge-component#32]
Using `defaultTickLineConfig: {hide: true}` does not hide the lines
A workaround is set the line colour with zero opacity #ffffff00 but I would assume that hiding the tick lines would also bring the labels a bit closer to the arc too

**Comment by antoniolago** [comment]
Thank you for reporting this, tick value hiding was not working too, fixed on 1.1.33

**Comment by antoniolago** [comment]
Hey @andrewjafa, I've just uploaded a version which should bring values of ticks close to arcs when hiding the lines

**Comment by andrewjafa** [comment]
Brilliant, looks great, thank you!
