### ISSUE TITLE
display custom label for sub arcs?

### ISSUE THREAD

**Issue by ezrnew** [antoniolago/react-gauge-component#33]
Hey, how can i change labels for sub arcs on a gauge? I tried to do it in the following way but it works only for the main label (J)
![image](https://github.com/antoniolago/react-gauge-component/assets/53041849/2a136e2b-799e-4afc-bd94-12739fc495e3)

The subarcs are always displayed with %.
I also tried the temperature example from readme but it doesnt work either; it results in typescript error.

**Comment by antoniolago** [comment]
Hey, thanks for reporting this, apparently I was just considering defaultTickValueConfig.formatTextValue but not the individual ticks configs, this is fixed on 1.1.34
