### ISSUE TITLE
Please add named export to library

### ISSUE THREAD

**Issue by chrisallday-dev** [antoniolago/react-gauge-component#53]
Hi, could you possibly add a named export to the library in addition to the default? I am in a situation where I require a named export for the project to work correctly.

**Comment by antoniolago** [comment]
Sorry for the delay, added named exports in v1.2.5
You can now import the component with
<code>
import GaugeComponent from 'react-gauge-component';
</code>
or
<code>
import { GaugeComponent } from 'react-gauge-component';
</code>

**Comment by chrisallday-dev** [comment]
Awesome work, thanks!
