### ISSUE TITLE
The order of precedence for default values is not as expected

### ISSUE THREAD

**Issue by f2971112** [antoniolago/react-gauge-component#65]
There should probably be a slightly different chain in places like that:

1. tick...Config (overrides any earlier config)
2. user default...Config (if no tick is defined, use user-defined defaults)
3. library default...Config (if neither tick nor user-defaults are defined, use library-defined defaults)

https://github.com/antoniolago/react-gauge-component/blob/ce1d7566511dc43adfb45abe720c6274fbc0f776/src/lib/GaugeComponent/hooks/labels.ts#L75

**Comment by antoniolago** [comment]
Hello, that makes total sense and it's fixed in v1.2.6, thanks for opening this =)
