### ISSUE TITLE
 The limit of a subArc must be greater than the limit of the previous subArc.

### ISSUE THREAD

**Issue by script8888** [antoniolago/react-gauge-component#9]
Hi, good work with the fork

Can you remove this error and allow a setup which we can use limit greater than the limit of previous subArc

My current design requires the limits to be in this order 39, 21, 25, 15
And when I input it, it throws this error: ` The limit of a subArc must be greater than the limit of the previous subArc.`

**Comment by antoniolago** [comment]
Hello @script8888, thanks for sharing your issue, the behavior of the subArcs rendering requires that the next subArc limit to be greater than the previous one or undefined for calculating subArcs length, but I think we can trade this error for a reorder of the subArcs by limits in crescent order, I'll add this soon but let me know if this is what you meant, also if you could share your component's code it would help make it clearer for me. Thanks.

**Comment by antoniolago** [comment]
Just uploaded a new version (1.0.1) with the requested feature, let me know if this works for you.

**Comment by script8888** [comment]
Ohhhh that makes sense now
guess I misunderstood it

Also, there are a lot of lint type errors when using it with typescript next js.
The "type" attribute which is supposed to be a string shows this lint error: 
```
Type '"semicircle"' is not assignable to type 'GaugeType | undefined'.ts(2322)
GaugeComponentProps.d.ts(27, 5): The expected type comes from property 'type' which is declared here on type 'IntrinsicAttributes & Partial<GaugeComponentProps>'
```
This is how I used it `<GaugeComponent type="semicircle" />`

So I had to import the `GaugeType` and use it like this `<GaugeComponent type={GaugeType.Semicircle} />` before the lint error went away

And the fixes to the other lint errors are making it compulsory to add the attribute even though I'm not making use of said attributes
I experience such in both the `arc` and `labels` attribute

**Comment by antoniolago** [comment]
Darn it, I forgot I tested just from .js file, I'll overhaul these typing issues, thanks.

**Comment by script8888** [comment]
awesome
overall you did a great job fixing the rerender issues

Thats awesome
Thanks

**Comment by antoniolago** [comment]
Now that you mentioned render issues, I went to check it and saw that after grafana gauge implementation some gauges are rerendering marks and arcs without needing to, I'll create a new issue and fix it.

**Comment by antoniolago** [comment]
For the types issue I created #11 and uploaded the fix in version 1.0.12, let me know if that works for you

**Comment by script8888** [comment]
now it shows this error on the import
`Cannot find module 'react-gauge-component' or its corresponding type declarations.ts(2307)`

**Comment by antoniolago** [comment]
I ended up adding back the error message (with more details) and adding the length property the same way it worked in the original project, with this I'm closing this issue, but please feel free to create more issues or contact me directly, thanks @script8888.

**Comment by script8888** [comment]
awesome man
it works fine now and doesn't require me to  add attributes I do not need to use

just a suggestion, but if you could add a range of values in the interface of the `type` attribute, so when I try to get suggestions in my ide it can show possible values I can put in for that attribute.

But yeah no more errors from my end to the extent at which I am using the component

**Comment by antoniolago** [comment]
Nice, happy it's working fine. 

Yeah, that's a fair point, I created #16 for that, thanks mate.
